### PR TITLE
About group not showing creator

### PR DESCRIPTION
**Pull request by sathomas**
screen shot 2015-01-26 at 9 51 30 am

### CODE REVIEW

**Comment by sathomas** [comment]
This PR fixes the issue in the front end code. I'm not sure if it would be better to fix it in Hilary. (That would definitely eliminate one network roundtrip request.) To @nicolaasmatthijs for comment/review.

**Comment by nicolaasmatthijs** [comment]
@sathomas : Can you go back in the Hilary codebase and check if we used to return the full creator profile as part of the profile feeds? I'm under the impression that we did, and that would also be a better way of resolving the issue.

**Comment by sathomas** [comment]
I looked at the current Hilary code, in `model.group.js` and saw this:

```
/**
 * The Group model.
 *
 * @param  {String}     tenantAlias                 The alias of the tenant this group belongs to
 * @param  {String}     id                          The globally unique principalId for this group. e.g.: g:cam:math-101
 * @param  {String}     displayName                 The display name of the group
 * @param  {Object}     [opts]                      Optional additional group properties
 * @param  {String}     [opts.visibility]           The visibility of the group
 * @param  {String}     [opts.joinable]             How the group can be joined
 * @param  {String}     [opts.description]          A longer description for the group
 * @param  {Number}     [opts.lastModified]         The lastModified date of the group
 * @param  {Number}     [opts.created]              The create date of the group
 * @param  {String}     [opts.createdBy]            The id of the user that created the group
 * @param  {String}     [opts.smallPictureUri]      The uri of the small picture. It will be made available at user.picture.smallUri
 * @param  {String}     [opts.mediumPictureUri]     The uri of the medium picture. It will be made available at user.picture.mediumUri
 * @param  {String}     [opts.largePictureUri]      The uri of the large picture. It will be made available at user.picture.largeUri
 */
```

I'll look through the history and see if that's been changed any time in the past

**Comment by sathomas** [comment]
Looks like it's always been just the user ID. Initial functionality added in this [commit](https://github.com/oaeproject/Hilary/commit/410dfb0270a1b15ed49069afa6b4859ad0493795). Although @simong did clarify the documentation [later](https://github.com/oaeproject/Hilary/commit/03e8dde2c30d6f25726757f713a612a25b94e956).

**Comment by nicolaasmatthijs** [comment]
There was a point in time where we modified all `getFullProfile` function to include the full user profile of the creator. However, that doesn't seem to be present for groups (anymore). The back-end code should be adjusted to include the full profile (e.g. `https://github.com/oaeproject/Hilary/blob/master/node_modules/oae-content/lib/api.js#L155`) and appropriate tests should be added. 

@sathomas : Can you create a Hilary ticket for this and either have a go at it yourself or assign to @stuartf ?

**Comment by sathomas** [comment]
Closing this in favor of Hilary issue https://github.com/oaeproject/Hilary/issues/1117

**Pull request closed without merging**
