### PR TITLE
Etherpad 1.5.6 work

### PR DESCRIPTION
**Pull request by simong**

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
@simong : Is this PR still valid?

**Comment by simong** [comment]
Yes, it's necessary for 1.5.6 as well. I'll rename the issue's title

**Comment by mrvisser** [comment]
@simong want me to review this for the bug bash?

**Comment by nicolaasmatthijs** [comment]
Sounds like that will be useful. Over to @mrvisser

**Comment by mrvisser** [comment]
@simong can you give an overview of why this change is being made? Also it will need a puppet-hilary PR to go along w/ it so we can pull it into the bug bash.

**Comment by simong** [comment]
Etherpad upgraded their version of socket.io which changed where the websocket is exposed.

IIRC, by default it will be exposed at `http://domain/socket.io` but we've [contributed a patch](https://github.com/ether/etherpad-lite/commit/45c1ad078bda7800cec1a81f2b8517adec93c43d) that exposes it at `http://baseURL/socket.io`. Because we embed etherpad using the URL: `http://tenantHost/etherpad/0` that baseURL will be `tenantHost/etherpad/0`.

I'll have a puppet-hilary branch ready that I'll push in a minute.

**Pull request merged**
