### PR TITLE
Top navigation buttons should have tooltip

### PR DESCRIPTION
**Pull request by sathomas**
All top navigation buttons should have a standard tooltip (e.g. Notifications, Sign out, etc.)

### CODE REVIEW

**Comment by sathomas** [comment]
I added a tooltip to the search icon as well. Not sure if that's desirable. Also, I positioned the tips below the icons so that the home tooltip doesn't obscure the notifications tooltip. That may not be ideal either. Ready for @nicolaasmatthijs to comment/review

**Comment by nicolaasmatthijs** [comment]
@sathomas : There's no need to use the Bootstrap tooltips for this. Would you be able to change this to use the standard title attribute tooltips?

**Comment by sathomas** [comment]
Home and Notifications already had `title` attributes. They're back now, along with added `title` attributes for Search and Sign out. To @nicolaasmatthijs

**Comment by nicolaasmatthijs** [comment]
Looks good. Merged.

**Pull request merged**
