### PR TITLE
Fix infinite loop in manage access widget

### PR DESCRIPTION
**Pull request by mrvisser**

### CODE REVIEW

**Comment by mrvisser** [comment]
Assign to @nicolaasmatthijs for review

**Comment by mrvisser** [comment]
@nicolaasmatthijs I think we should get this merged ASAP. Updated the title to hopefully reflect importance

**Comment by mrvisser** [comment]
@sathomas feel free to pick this up and review if you get here first. I had only assigned it to Nico because he had made a comment about it in Slack.

**Comment by sathomas** [comment]
+1 for merging. I can review and merge if you like

**Comment by sathomas** [comment]
guess we're thinking alike :)

**Comment by sathomas** [comment]
Verified and merged

**Comment by nicolaasmatthijs** [comment]
Sorry, I completely missed this. PR looks good though.

**Pull request merged**
