### PR TITLE
Resetpassword

### PR DESCRIPTION
**Pull request by stevenxzhou**
For Front-end.

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
@taybson : Before I do a detailed code review of this PR, I'm going to send this over to our designer for some design input around the user interface.

**Comment by taybson** [comment]
Hi @nicolaasmatthijs,

I know there is still some issues for the version I pushed on Github. I am currently in China for vacation with my family, There are many friends and relatives for me to see since It’s been 1.5 years since I went to US. However, I’ll find some time to finish my work and make it work ASAP. Sorry for the procrastination.

Thank you,
Steven.

**Comment by nicolaasmatthijs** [comment]
@taybson : No worries. Taking the time to see family and friends is much more important. We'll work through things once you're ready :)

**Comment by sallakarppinen** [comment]
I'm closing this in favour of the newer pull request for the same.

**Pull request closed without merging**
