### PR TITLE
Use our own URL expander and update the jQuery oembed plugin

### PR DESCRIPTION
**Pull request by simong**
UI counter part of https://github.com/oaeproject/Hilary/pull/1139

### CODE REVIEW

**Comment by simong** [comment]
I'm marking this as `On hold` as it's currently relying on a PR against the jquery-oembed-all repository: https://github.com/nfl/jquery-oembed-all/pull/22

**Comment by mrvisser** [comment]
@simong things seem to be moving a bit slow on their end. Did you want to switch to a github clone for now?

**Comment by simong** [comment]
I'm OK with that. My copy of the changes are already included in this PR

**Comment by mrvisser** [comment]
Ah right, this isn't NPM.

**Comment by mrvisser** [comment]
@simong can you add a note in the header of the oembed file that it is forked, with a reference to the external PR that is pending review?

**Pull request merged**
