### PR TITLE
Skinning error in configurable landing pages

### PR DESCRIPTION
**Pull request by nicolaasmatthijs**
Skinning isn't being applied correctly to the lower left block. 

screen shot 2015-01-16 at 10 09 56 am

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
Added a fix. Over to @sathomas for review.

**Comment by sathomas** [comment]
I think there's still an issue with the icon colors. For Georgia Tech, I think the icon color should be `#eeb211` since that's the hover color and the color of the play control in the video. Or maybe it's supposed to be gray? (At the very least, it shouldn't be blue.) Back to @nicolaasmatthijs

**Comment by nicolaasmatthijs** [comment]
That's not a bug. The title color for that block is configured to be blue, which means that the icon will be blue as well. Feel free to reconfigure the title color for that block to the yellow of the icons.

**Comment by nicolaasmatthijs** [comment]
Back to @sathomas for review

**Comment by sathomas** [comment]
Sorry if I'm missing something, but there is absolutely nothing in the current Georgia Tech skin that is configured as blue. Is there maybe a variable that isn't exposed to the admin skinning interface that should be?

voila_capture 2015-01-16_10-46-30_am

**Comment by nicolaasmatthijs** [comment]
It's part of the landing page configuration under Modules --> OAE Tenant Module. A proper admin UI for this is scheduled for the next release.

**Comment by sathomas** [comment]
Ah. Got it. Fixed the Georgia Tech page and merged the PR.

**Pull request merged**
