### PR TITLE
(Issue 4040) TopNav improvements / Combine index+me pages into root path

### PR DESCRIPTION
**Pull request by mrvisser**
This builds on to inviting guests due to significant conflict. It incorporates the followup from #4040 as well as additional changes to merge w/ inviting guests

### CODE REVIEW

**Comment by mrvisser** [comment]
I've put this on hold to await inviting guests

**Comment by mrvisser** [comment]
This is no longer on hold. To @nicolaasmatthijs for review.

FYI, this was bashed on last Wednesday's bug bash, and is dependent on https://github.com/oaeproject/Hilary/pull/1230

**Comment by mrvisser** [comment]
If it helps, this already went through some review in #3992 . The followup required from the last round there was taken into consideration in my commits here.

**Comment by nicolaasmatthijs** [comment]
Finished review. Back to @mrvisser for follow-up

**Comment by mrvisser** [comment]
There is an issue with auto-login on the signup page that I'm working on.

Also just found this when there is single-external-auth and in mobile device width:

image

**Comment by mrvisser** [comment]
Followed up, back to @nicolaasmatthijs

**Comment by nicolaasmatthijs** [comment]
Finished review. Back to @mrvisser for follow-up

**Comment by mrvisser** [comment]
Followed up, back to @nicolaasmatthijs

**Comment by nicolaasmatthijs** [comment]
Looks good. Merged

**Pull request merged**
