### PR TITLE
(CountryCode) Add country code to admin UI

### PR DESCRIPTION
**Pull request by mrvisser**
On hold as this builds on topnavigation enhancements.

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
Finished review. Back to @mrvisser for follow-up.

**Comment by mrvisser** [comment]
I've followed up as much as I can for the bug bash unfortunately. I'll have to finish followup and perhaps bug bash again later. I'll create a branch that contains everything that is done so far.

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Can you rebase this against master as well? The navigation improvements have now been merged.

**Comment by mrvisser** [comment]
Followed up, back to @nicolaasmatthijs

**Comment by nicolaasmatthijs** [comment]
Followed up and merged

**Pull request merged**
